version: '3'

services: 
    swagger:
        image: swaggerapi/swagger-ui
        ports:
            - 8081:8080
        volumes: 
            - .:/tmp
        environment: 
            SWAGGER_JSON: '/tmp/swagger.yml'
            BASE_URL: '/swagger'
    rabbitmq:
        image: rabbitmq:management
        ports:
            - "15672:15672"
            - "5672:5672"
        restart: always
        container_name: "rabbitmq"
        environment:
            - RABBITMQ_NODENAME=rabbit@rabbitmq
        volumes:
            - ./rabbitmq:/var/lib/rabbitmq
