version: '3'

services: 
    swagger:
        image: swaggerapi/swagger-ui
        ports:
            - 8081:8080
        volumes: 
            - .:/tmp
        environment: 
            SWAGGER_JSON: '/tmp/swagger.yml'
            BASE_URL: '/swagger'
