version: '3'

services: 
    swagger:
        image: swaggerapi/swagger-ui
        ports:
            - 8081:8080
        volumes: 
            - .:/tmp
        environment: 
            SWAGGER_JSON: '/tmp/swagger.yml'
            BASE_URL: '/swagger'
    rabbitmq:
        image: rabbitmq:management
        ports:
            - "15672:15672"
            - "5672:5672"
        restart: always
        container_name: "rabbitmq"
        environment:
            - RABBITMQ_NODENAME=rabbit@rabbitmq
        volumes:
            - ./rabbitmq:/var/lib/rabbitmq
        # healthcheck:
        #     test: ["CMD", "curl", "-f", "http://localhost:5672"]
        #     interval: 5s #每幾秒重試一次
        #     timeout: 10s #每次重試的 timeout
        #     retries: 3 #重試幾次失敗就視為 unhealthy
    # server:
    #     build: .
    #     ports:
    #         - 9999:9999
    #     depends_on:
    #         - rabbitmq
