openapi: '3.0.2'
info:
  title: Recodar RESTful API
  version: '1.0'
servers:
  - url: https://localhost:9999
components:
  schemas:
    AccessToken:
      type: object
      properties:
        token:
          type: string

paths:
  /api/v1/auth/line:
    get:
      summary: 透過 Line 認證
      tags:
        - Authorization
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessToken'
  
  /api/v1/auth/google:
    get:
      summary: 透過 Google 認證
      tags:
        - Authorization
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessToken'

            